name: etl_warehouse
version: "1.0.0"

profile: warehouse

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  etl_warehouse:
    silver:
      +schema: sil
    gold:
      +schema: gold
      +materialized: table

seeds:
  etl_warehouse:
    gold__pnl__dim_cost_category:
      +schema: gold__pnl

snapshots:
  etl_warehouse:
    +target_schema: sil
